#!/usr/bin/ruby

require 'open3'

FORMULAES = %w(
  chruby
  fzf
  git
  ruby-build
  ruby-install
  wget
).freeze

APPLICATIONS = %w(
  google-chrome
  iterm2
  spotify
  spotifree
).freeze

begin
  `brew -v`
rescue Errno::ENOENT
  # Install package manager
  `$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)`
end

missing_formulaes = FORMULAES - `brew list`.split("\n")
unless missing_formulaes.empty?
  command = "brew install #{missing_formulaes.join(' ')}"
  _, stderr, status = Open3.capture3(command)
  puts stderr unless status
end

# Post-install scripts
#   Install useful key bindings and fuzzy completion
`$(brew --prefix)/opt/fzf/install`

missing_applications = APPLICATIONS - `brew cask list`.split("\n")
unless missing_applications.empty?
  `brew cask install #{missing_applications.join(' ')}`
end
